agro_laravel_2019/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/welcome', function () {
    return view('welcome');
});

Route::resource('participantes', 'ParticipanteController');

Route::get('/registro', function () {
    return view('participantes.create');
});


Route::get('/', function () {
    return view('landingPage.index');
});

agro_laravel_2019/app/Participante.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Participante extends Model
{
    protected $fillable = ['nombre', 'apellidoPaterno', 'apellidoMaterno',
    'email','genero','edad','celular','ocupacion', 'pais', 'estado', 'ciudad',
     'codigoPostal', 'direccion', 'nombreEmpresa'];
}

agro_laravel_2019/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

agro_laravel_2019/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

agro_laravel_2019/app/Http/Controllers/ParticipanteController.php
<?php

namespace App\Http\Controllers;

use App\Participante;
use Illuminate\Http\Request;

class ParticipanteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $participantes = Participante::latest()->paginate(5);
  
        return view('participantes.index',compact('participantes'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('participantes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre' => 'required', 
            'apellidoPaterno' => 'required', 
            'apellidoMaterno' => 'required',
            'email' => 'required',
            'genero' => 'required',
            'edad' => 'required',
            'celular' => 'required',
            'ocupacion' => 'required',
            'pais' => 'required', 
            'estado' => 'required', 
            'ciudad' => 'required',
            'codigoPostal' => 'required',
            'direccion' => 'required',
            'nombreEmpresa' => 'required',
        ]);
  
        Participante::create($request->all());
   
        return redirect()->route('participantes.index')
                        ->with('success','Participante creado correctamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Participante  $participante
     * @return \Illuminate\Http\Response
     */
    public function show(Participante $participante)
    {
        return view('participantes.show',compact('participante'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Participante  $participante
     * @return \Illuminate\Http\Response
     */
    public function edit(Participante $participante)
    {
        return view('participantes.edit',compact('participante'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Participante  $participante
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Participante $participante)
    {
        $request->validate([
            'nombre' => 'required', 
            'apellidoPaterno' => 'required', 
            'apellidoMaterno' => 'required',
            'email' => 'required',
            'genero' => 'required',
            'edad' => 'required',
            'celular' => 'required',
            'ocupacion' => 'required',
            'pais' => 'required', 
            'estado' => 'required', 
            'ciudad' => 'required',
            'codigoPostal' => 'required',
            'direccion' => 'required',
            'nombreEmpresa' => 'required',
        ]);
  
        $participante->update($request->all());
  
        return redirect()->route('participantes.index')
                        ->with('success','Participante actualizado correctamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Participante  $participante
     * @return \Illuminate\Http\Response
     */
    public function destroy(Participante $participante)
    {
        $participante->delete();
  
        return redirect()->route('participantes.index')
                        ->with('success','Participant3 eliminado correctamente');
    }

    public function pdf(){
      
       
    }
}

agro_laravel_2019/resources/views/landingPage/banner.blade.php
<!-- Section Content -->
<section id="home" class="g-bg-img-hero g-pos-rel u-bg-overlay  g-pt-150" style="background-image: url({{asset('/img/recursosAgro/bannerAgro.png')}});">
        <div class="container g-max-width-750 u-bg-overlay__inner g-color-white g-mb-60">
          <!-- Countdown v4 
          <div class="js-countdown text-center text-uppercase u-countdown-v4 g-mb-40 g-mb-70--md"
               data-end-date="2019/08/22"
               data-month-format="%m"
               data-days-format="%D"
               data-hours-format="%H"
               data-minutes-format="%M"
               data-seconds-format="%S">
            <div class="d-inline-block g-font-size-12 g-px-10 g-px-50--md g-py-15">
              <div class="js-cd-days g-font-size-20 g-font-size-40--md g-font-weight-700 g-line-height-1 g-mb-5">33</div>
              <span>DÍAS</span>
            </div>

            <div class="d-inline-block g-font-size-12 g-brd-left g-brd-white-opacity-0_4 g-px-10 g-px-60--md g-py-15">
              <div class="js-cd-hours g-font-size-20 g-font-size-40--md g-font-weight-700 g-line-height-1 g-mb-5">01</div>
              <span>HORAS</span>
            </div>

            <div class="d-inline-block g-font-size-12 g-brd-left g-brd-white-opacity-0_4 g-px-10 g-px-60--md g-py-15">
              <div class="js-cd-minutes g-font-size-20 g-font-size-40--md g-font-weight-700 g-line-height-1 g-mb-5">52</div>
              <span>MINUTOS</span>
            </div>

            <div class="d-inline-block g-font-size-12 g-brd-left g-brd-white-opacity-0_4 g-px-10 g-px-50--md g-py-15">
              <div class="js-cd-seconds g-font-size-20 g-font-size-40--md g-font-weight-700 g-line-height-1 g-mb-5">52</div>
              <span>SEGUNDOS</span>
            </div>
          </div>-->
          <!-- End Countdown v4 -->
          <div class="js-countdown u-countdown-v5 text-center" data-end-date="2019/08/22" data-days-format="%D" data-hours-format="%H" data-minutes-format="%M" data-seconds-format="%S">
            <div class="d-inline-block g-mx-20 g-mb-40">
              <div class="js-cd-days g-font-size-56 g-font-weight-300 g-line-height-1"></div>
              <span>DÍAS</span>
            </div>
          
            <div class="hidden-down d-inline-block align-top g-font-size-28 g-font-weight-200 g-line-height-1_8">|</div>
          
            <div class="d-inline-block g-mx-20 g-mb-40">
              <div class="js-cd-hours g-font-size-56 g-font-weight-300 g-line-height-1"></div>
              <span>HORAS</span>
            </div>
          
            <div class="hidden-down d-inline-block align-top g-font-size-28 g-font-weight-200 g-line-height-1_8">|</div>
          
            <div class="d-inline-block g-mx-20 g-mb-40">
              <div class="js-cd-minutes g-font-size-56 g-font-weight-300 g-line-height-1"></div>
              <span>MINUTOS</span>
            </div>
          
            <div class="hidden-down d-inline-block align-top g-font-size-28 g-font-weight-200 g-line-height-1_8">|</div>
          
            <div class="d-inline-block g-mx-20 g-mb-40">
              <div class="js-cd-seconds g-font-size-56 g-font-weight-300 g-line-height-1"></div>
              <span>SEGUNDOS</span>
            </div>
          </div>
          <!--<h2 class="text-center text-uppercase h2 g-font-weight-700 g-font-size-40 g-font-size-60--md g-color-white g-mb-30 g-mb-70--md">UI &amp; UX Design 2017</h2> -->
            <img style="max-width: 100%; height: auto; width: auto;"
            src="{{asset('/img/recursosAgro/agroalimentariazac_logox5.png')}}" alt=""  align-items: g-absolute-centered;">
          <div class="row">
            <div class="col-sm-6 col-md-4 text-center text-md-left g-mb-30 g-mb-0--md">
              <div class="media">
                <div class="media-left d-flex align-self-center g-hidden-sm-down g-mr-20">
                  <i class="fa fa-calendar g-font-size-27 g-color-white-opacity-0_5"></i>
                </div>

                <div class="media-body text-uppercase">
                
                  <h3 class="h3 g-font-size-15 g-color-white mb-0">22, 23 Y 24 Agosto 2019</h3>

                </div>
              </div>
            </div>

            <div class="col-sm-6 col-md-5 text-center text-md-left g-mb-30 g-mb-0--md">
              <div class="media">
                <div class="media-left d-flex align-self-center g-hidden-sm-down g-mr-20">
                  <i class="fa fa-map-marker g-font-size-27 g-color-white-opacity-0_5"></i>
                </div>

                <div class="media-body text-uppercase">
                
                  <h3 class="h3 g-font-size-15 g-color-white mb-0">Palacio de Convenciones, Zacatecas</h3>
                </div>
              </div>
            </div>

            <div class="col-md-3 text-center text-md-right">
             <!--<a class="btn btn-lg text-uppercase u-btn-white g-font-weight-700 g-font-size-11 g-color-white--hover
               g-bg-primary--hover g-brd-none rounded-0 g-py-18 g-px-20" href="#registro">REGISTRATE AHORA</a>--> 
               <a href="#registro" class="btn btn-md u-btn-primary g-mr-10 g-mb-15">REGISTRATE AHORA</a>
            </div>
          </div>
        </div>

        <div class="container u-bg-overlay__inner g-bottom-minus-70 px-0">
          <div class="row u-shadow-v23 g-theme-bg-blue-dark-v2 mx-0">
            <div class="col-md-6 px-0">
              <div class="js-carousel text-center u-carousel-v5 g-overflow-hidden h-100 g-max-height-50vh"
                   data-infinite="true"
                   data-arrows-classes="u-arrow-v1 g-absolute-centered--y g-width-40 g-height-40 g-font-size-20 g-color-white g-color-primary--hover g-bg-primary g-bg-white--hover g-transition-0_2 g-transition--ease-in"
                   data-arrow-left-classes="fa fa-angle-left g-left-0"
                   data-arrow-right-classes="fa fa-angle-right g-right-0">
                <div class="js-slide g-bg-img-hero g-min-height-50vh" style="background-image: url({{asset('/img/recursosAgro/aboutImages/about2.png')}});"></div>

               
              </div>
            </div>

            <div class="col-md-6 d-flex g-min-height-50vh g-theme-color-gray-dark-v1 g-px-50 g-py-80 g-py-50--md g-py-20--lg">
              <div class="align-self-center w-100">
                <h2 class="text-uppercase g-font-weight-700 g-font-size-30 g-color-primary g-mb-10">Agroalimentaria Zacatecas 2019</h2>
                <h3 class="text-uppercase g-font-weight-500 g-font-size-13 g-color-white g-mb-20">Zacatecas, la potencia agroalimentaria de México</h3>
                <p class="g-font-size-14">Por segunda ocasión en el centro-norte del país, el Gobierno del Estado en conjunto con los productores de la cadena agroalimentaria, te invitan a ser parte del evento que será nuevamente punto de encuentro para que México y el mundo conozcan la oportunidad de negocios que ofrece el Campo Zacatecano</p>
                <p class="g-font-size-14 mb-0"></p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- End Section Content -->

agro_laravel_2019/resources/views/landingPage/head.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Title -->
    <title>Agroalimentaria Zacatecas 2019</title>

    <!-- Required Meta Tags Always Come First -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- Favicon -->
    <link rel="shortcut icon" href="{{asset('/img/recursosAgro/favicon.png')}}">

    <!-- Google Fonts -->
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:400,300,500,600,700,800">

    <!-- CSS Global Compulsory -->
    <link rel="stylesheet" href="{{asset('/vendor/bootstrap/bootstrap.min.css')}}">

    <!-- CSS Implementing Plugins -->
    <link rel="stylesheet" href="{{asset('/vendor/icon-awesome/css/font-awesome.min.css')}}">
    <link rel="stylesheet" href="{{asset('/vendor/icon-line/css/simple-line-icons.css')}}">
    <link rel="stylesheet" href="{{asset('/vendor/icon-hs/style.css')}}">
    <link rel="stylesheet" href="{{asset('/vendor/hamburgers/hamburgers.min.css')}}">
    <link rel="stylesheet" href="{{asset('/vendor/animate.css')}}">
    <link rel="stylesheet" href="{{asset('/vendor/slick-carousel/slick/slick.css')}}">
    <link rel="stylesheet" href="{{asset('/vendor/fancybox/jquery.fancybox.css')}}">
    <link  rel="stylesheet" href="{{asset('/vendor/jquery-ui/themes/base/jquery-ui.min.css')}}">

      <!-- CSS Implementing Plugins -->
      <link  rel="stylesheet" href="{{asset('/vendor/dzsparallaxer/dzsparallaxer.css')}}">
      <link  rel="stylesheet" href="{{asset('/vendor/dzsparallaxer/dzsscroller/scroller.css')}}">
      <link  rel="stylesheet" href="{{asset('/vendor/dzsparallaxer/advancedscroller/plugin.css')}}">
    

    <!-- CSS Template -->
    <link rel="stylesheet" href="{{asset('/css/styles.op-event.css')}}">

    <!-- CSS Customization -->
    <link rel="stylesheet" href="{{asset('/css/custom.css')}}">
  </head>

  <body>
    <main>
        

agro_laravel_2019/resources/views/landingPage/header.blade.php
 <!-- Header v1 -->
 <header id="js-header" class="u-header u-header--sticky-top u-header--change-appearance g-z-index-9999"
        data-header-fix-moment="100">
    <div class="light-theme u-header__section g-bg-darkblue-opacity-0_7 g-transition-0_3 g-py-10"
        data-header-fix-moment-exclude="light-theme g-bg-darkblue-opacity-0_7"
        data-header-fix-moment-classes="dark-theme u-shadow-v18 g-bg-white-opacity-0_9">
    <nav class="navbar navbar-expand-lg g-py-0">
        <div class="container g-pos-rel">
        <!-- Logo -->
        <a href="#" class="js-go-to navbar-brand u-header__logo"
            data-type="static">
            <img class="u-header__logo-img u-header__logo-img--main d-block" src="{{asset('/img/recursosAgro/agroLogoInicio.png')}}" alt="Image description"
                data-header-fix-moment-exclude="d-block"
                data-header-fix-moment-classes="d-none"
                style="height: 150; width: 60;">

            <img class="u-header__logo-img u-header__logo-img--main d-none" src="{{asset('/img/recursosAgro/agroLogoInicio.png')}}" alt="Image description"
                data-header-fix-moment-exclude="d-none"
                data-header-fix-moment-classes="d-block">
        </a>
        <!-- End Logo -->

        <!-- Navigation -->
        <div class="collapse navbar-collapse align-items-center flex-sm-row" id="navBar" data-mobile-scroll-hide="true">
            <ul id="js-scroll-nav" class="navbar-nav text-uppercase g-font-weight-700 g-font-size-11 g-pt-20 g-pt-5--lg ml-auto">
            <li class="nav-item g-mr-15--lg g-mb-7 g-mb-0--lg active">
                <a href="#home" class="nav-link p-0">INICIO <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item g-mx-15--lg g-mb-7 g-mb-0--lg">
                <a href="#ponentes" class="nav-link p-0">PONENTES</a>
            </li>
            <li class="nav-item g-mx-15--lg g-mb-7 g-mb-0--lg">
                <a href="#schedule" class="nav-link p-0">PROGRAMA DEL EVENTO</a>
            </li>
            <li class="nav-item g-mx-15--lg g-mb-7 g-mb-0--lg">
                <a href="#expositores" class="nav-link p-0">EXPOSITORES</a>
            </li>
            <li class="nav-item g-mx-15--lg g-mb-7 g-mb-0--lg">
                <a href="#sponsors" class="nav-link p-0">PATROCINADORES Y ALIADOS</a>
            </li>
            <li class="nav-item g-mx-15--lg g-mb-7 g-mb-0--lg">
                <a href="#registro" class="nav-link p-0">REGISTRO DE PARTICIPANTES</a>
                </li>
            <li class="nav-item g-mx-15--lg g-mb-7 g-mb-0--lg">
                <a href="#contact" class="nav-link p-0">CONTACTO</a>
            </li>
            </ul>
        </div>
        <!-- End Navigation -->

        <!-- Responsive Toggle Button -->
        <button class="navbar-toggler btn g-line-height-1 g-brd-none g-pa-0 g-pos-abs g-top-15 g-right-0" type="button"
                aria-label="Toggle navigation"
                aria-expanded="false"
                aria-controls="navBar"
                data-toggle="collapse"
                data-target="#navBar">
            <span class="hamburger hamburger--slider">
            <span class="hamburger-box">
                <span class="hamburger-inner"></span>
            </span>
            </span>
        </button>
        <!-- End Responsive Toggle Button -->
        </div>
    </nav>
    </div>
</header>
<!-- End Header v1 -->

agro_laravel_2019/resources/views/participantes/create.blade.php
@extends('participantes.layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Crear nuevo participante</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('participantes.index') }}"> Regresar</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> Hubo un problema con los datos que escribiste.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('participantes.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre:</strong>
                <input type="text" name="nombre" class="form-control" placeholder="Nombre">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Apellido paterno:</strong>
                <input class="form-control" style="height:150px" name="apellidoPaterno" placeholder="Apellido paterno"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Apellido materno:</strong>
                <input type="text" name="apellidoMaterno" class="form-control" placeholder="Apellido materno">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>E-mail:</strong>
                <input class="form-control" style="height:150px" name="email" placeholder="E-mail"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Género:</strong>
                <input type="text" name="genero" class="form-control" placeholder="Género">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Edad:</strong>
                <input class="form-control" style="height:150px" name="edad" placeholder="Edad"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Número celular:</strong>
                <input type="text" name="celular" class="form-control" placeholder="Número celular">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Ocupación:</strong>
                <input class="form-control" style="height:150px" name="ocupacion" placeholder="Ocupación"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>País:</strong>
                <input type="text" name="pais" class="form-control" placeholder="País">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Estado:</strong>
                <input class="form-control" style="height:150px" name="estado" placeholder="Estado"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Ciudad:</strong>
                <input type="text" name="ciudad" class="form-control" placeholder="Ciudad">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Código Postal:</strong>
                <input class="form-control" style="height:150px" name="codigoPostal" placeholder="Código Postal"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Dirección:</strong>
                <input class="form-control" style="height:150px" name="direccion" placeholder="Dirección"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre de empresa:</strong>
                <input class="form-control" style="height:150px" name="nombreEmpresa" placeholder="Nombre de empresa"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Enviar</button>
        </div>
    </div>
   
</form>
@endsection

agro_laravel_2019/resources/views/participantes/edit.blade.php
@extends('participantes.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar Participante</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('participantes.index') }}"> Regresar</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> Hubo un problema con los datos que escribiste.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('participantes.update',$participante->id) }}" method="POST">
        @csrf
        @method('PUT')
   
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Nombre:</strong>
                    <input type="text" name="nombre" value="{{ $participante-> nombre}}" class="form-control" placeholder="Nombre">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Apellido paterno:</strong>
                    <input class="form-control" style="height:150px" name="apellidoPaterno" value="{{ $participante-> apellidoPaterno}}" placeholder="Apellido paterno"></input>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Apellido materno:</strong>
                    <input type="text" name="apellidoMaterno" value="{{ $participante-> apellidoMaterno}}" class="form-control" placeholder="Apellido materno">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>E-mail:</strong>
                    <input class="form-control" style="height:150px" name="email" value="{{ $participante-> email}}" placeholder="E-mail"></input>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Género:</strong>
                    <input type="text" name="genero" value="{{ $participante-> genero}}" class="form-control" placeholder="Género">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Edad:</strong>
                    <input class="form-control" style="height:150px" name="edad" value="{{ $participante-> edad}}" placeholder="Edad"></input>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Número celular:</strong>
                    <input type="text" name="celular" value="{{ $participante-> celular}}" class="form-control" placeholder="Número celular">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Ocupación:</strong>
                    <input class="form-control" style="height:150px" name="ocupacion" value="{{ $participante-> ocupacion}}" placeholder="Ocupación"></input>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>País:</strong>
                    <input type="text" name="pais" value="{{ $participante-> pais}}" class="form-control" placeholder="País">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Estado:</strong>
                    <input class="form-control" style="height:150px" name="estado" value="{{ $participante-> estado}}" placeholder="Estado"></input>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Ciudad:</strong>
                    <input type="text" name="ciudad" value="{{ $participante-> ciudad}}" class="form-control" placeholder="Ciudad">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Código Postal:</strong>
                    <input class="form-control" style="height:150px" name="codigoPostal" value="{{ $participante-> codigoPostal}}" placeholder="Código Postal"></input>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Dirección:</strong>
                    <input class="form-control" style="height:150px" name="direccion" value="{{ $participante-> direccion}}" placeholder="Dirección"></input>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Nombre de empresa:</strong>
                    <input class="form-control" style="height:150px" name="nombreEmpresa" value="{{ $participante-> nombreEmpresa}}" placeholder="Nombre de empresa"></input>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Enviar</button>
            </div>
        </div>
   
    </form>
@endsection

agro_laravel_2019/resources/views/participantes/expositores.blade.php
 <!-- Section Content -->
  <section id="expositores" class="g-theme-bg-gray-light-v1 g-py-100">
    <div>
      <h3>EXPOSITORES</h3>
    </div>
  </section>
  <!-- End Section Content -->

agro_laravel_2019/resources/views/participantes/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Registro de participantes | Agroalimentaria Zacatecas 2019</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
  
<div class="container">
    @yield('content')
</div>
   
</body>
</html>